CREATE TABLE IF NOT EXISTS GOODS (
    GOODS_ID NUMBER(8),
    GOODS_NAME VARCHAR2(200 CHAR) NOT NULL,
    REGULAR_PRICE NUMBER(6) NOT NULL,
    APPLIED_TAX_PRICE NUMBER(6) NOT NULL,
    SALE_UNIT VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT goods_id_pk PRIMARY KEY (GOODS_ID)
);